modules_dir = "artifacts/"

[[module]]
    name = "local_storage"

    [module.wasi]
    preopened_files = ["./sites"]
    # this is an alias to a full path for the sites dir
    mapped_dirs = { "sites" = "./sites" }

[[module]]
    name = "curl_adapter"
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "facade"
    logger_enabled = true

